Oracle DATABASE
DDL  DATA DEFINITION LANGUAGE:-  ALTER,CONTROL,DROP ,TRUNCATE ,RENAME
DML  DATA MANIPULATION LANGUAGE: INSERT ,DELETE,UPDATE,MERGE
DRL  DATA RETRIVAL LANGUAGE : SELECT
TCL  TRANSACTION CONTROL LANGUAGE : COMMIT,ROLLBACK,SAVEPOINT
DCL  DATA CONTROL LANGUAGE : GRANT ,REVOKE

CONSTRAINTS IN ORACLE :- PK,FK,NOT NULL,CHECK,UNIQUE
SELECT STATEMENTS IN SQLCODE
SINGLE ROW FUNCTIONS
JOINS :- INNER, LEFT,RIGHT,OUTER FULL,SELF JOINS
AGGREGATE FUNCTION :- MIN,MAX,AVG,COUNT,GROUP BY,HAVING
SUB QUERY
SET OPERATOR :- UNION,UNION ALLL,INTERSECT,MINUS
ANALYTICAL/WINDOWS FUNCTION IN SQL
VIEWS,MATERIALIZED VIEWS
INDEXES IN Oracle
MERGE STATEMENTS
REGULAR EXPRESSION
PERFORMANCE TUNING  ;

DATA TYPE :-
 1. NUMERIC :
	 NUMBER (8),
	 NUMBER (8,2),
	 NUMBER (2,2),
 2. CHAR :
     CHAR
	 VARCHAR()
	 VARCHAR2()     4000 BYTES 
 3. DATE :
     DATE 10-JANVERY-2024
############################################################
 
 HOW TO GET BACKUP FROM DATABASE
 1. BKP A TABLE(create i t)
 2.TRUNCATE BASE TABLE (clean it original)
 3.MODIFY DATA TYPE (modify the table as per requied)
 4.RESTORE THE DATA 
 5.DROP BKP TABLE
 EX:- CREATE TABLE (BKP_TABLE_NAME) AS SELECT * FROM (TABLE_NAME)
      CREATE TABLE (BKP_TABLE_NAME) AS SELECT * FROM (TABLE_NAME) WHERE 1=2;
	  ( THIS WILL BE CRATE THE STRUCTURE ONLY)
	  TIME (1:02:49)

CONSTRAINTS IN ORACLE;
======================

DATA VALIDATION BEFORE INSERTING THE DATA INTO THE table

1.  PRIMARY KEY
 - IT WILL NOT ALLOW DUPLICATE VALUES
 - IT WILL NOT ALLOW NULL
 - ONLY ON PRIMARY KEY IN A TABLE 
  
--  composite KEY : combination of two columns is called composite key.

  
 
2. NOT NULL       *MANDATORY
 - IT WILL NOT ALLOW NULL VALUE
 - IT WILL ALLOW DUPLICATE
 
3. UNIQUE
 - IT WILL NOT ALLOW DUPLICATE
 - IT WILL ALLOW NULL

4. CHECK
 - DATE VALIDATION
   CHECK(AGE => 18)
5. FOREIGN KEY 
 - RELATIONSHIP BETWEEN TWO TABLES
 - IT WILL ACCEPT DUPLICATE VALUE
 - IT SHOULD BE PRIMARY KEY IN ANOTHER TABLE
 - ANY NO OF FOREIGN KEY IN A TABLE  
   -- FOREGIN KEY(CITY_ID) REFERENCES CITY(CITY_ID)
   
 VIOLATION :
  INTEGRITY CONSTRAINTS VOILATED - PARENT KEY NOT FOUND
  

 BACKUP DATA ALL DETAILS 
 CREATE TABLE (GIVE_NEW_NAME_BACKUP) AS SELECT * FROM (TABLE NAME ) ; ( IT WILL BE CRATE SAME TABLE ONLY ) 
 CREATE TABLE (TABLE_NAME ) AS SELECT * FROM (EXENSTING_TABLE ) WHERE 1=2; ( IT WILL CREATE THE STRUCTURE OF THE TABLE )
 TRUNCATE  TABLE (TABLE_NAME ) (WHILE WE DOING THIS WE CANN'T ROLL BACK , IT IS DDL COMMAND )